name: CI with Cache Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: prime-cache-64297e2
      id: cache-64297e2
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: cache-64297e2
    - name: Echo cache result
      run: echo "Cache result:${{ steps.cache-64297e2.outputs.cache-hit }}"
    - name: Install dependencies
      run: npm ci
